#Import the required libraries
from tkinter import *
import webbrowser

#Create an instance of tkinter frame
win = Tk()
#win.geometry("400x700")
#win.resizable(width=False,height=False)
win.iconbitmap('c:/Users/gf/Downloads/abc.ico')
win.title('Social Media')

#Define a callback function
def callback(url):
   webbrowser.open_new_tab(url)

#Create a Label to display the link
imagetest1 = PhotoImage(file="c:/Users/gf/Downloads/ig1.png")
imagetest2 = PhotoImage(file="c:/Users/gf/Downloads/facebook.png")
imagetest3 = PhotoImage(file="c:/Users/gf/Downloads/twitter.png")
imagetest4 = PhotoImage(file="c:/Users/gf/Downloads/Linked.png")
imagetest5 = PhotoImage(file="c:/Users/gf/Downloads/Discord.png")
imagetest6 = PhotoImage(file="c:/Users/gf/Downloads/pinterest.png")
imagetest7 = PhotoImage(file="c:/Users/gf/Downloads/reddit.png")
imagetest8 = PhotoImage(file="c:/Users/gf/Downloads/youtube.png")
imagetest9 = PhotoImage(file="c:/Users/gf/Downloads/whatsapp.png")
imagetest10 = PhotoImage(file="c:/Users/gf/Downloads/snapchat.png")
imagetest11 = PhotoImage(file="c:/Users/gf/Downloads/quora.png")
imagetest12 = PhotoImage(file="c:/Users/gf/Downloads/medium.png")
imagetest13 = PhotoImage(file="c:/Users/gf/Downloads/wechat.png")
imagetest14 = PhotoImage(file="c:/Users/gf/Downloads/stackoverflow.png")
imagetest15 = PhotoImage(file="c:/Users/gf/Downloads/piazza.png")
link1 =Button(win, text="Instagram",font=('Helveticabold', 15), fg="blue",padx=20,borderwidth=20,compound="top",image=imagetest1, cursor="hand2")
link1.grid(row=1,column=0)
link2 =Button(win, text="Facebook",font=('Helveticabold', 15), fg="blue",padx=20,image=imagetest2,compound="top", cursor="hand2")
link2.grid(row=1,column=1)
link3 =Button(win, text="Twitter",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest3, cursor="hand2")
link3.grid(row=1,column=2)
link4 =Button(win, text="Linkedln",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest4, cursor="hand2")
link4.grid(row=1,column=3)
link5 =Button(win, text="Discord",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest5, cursor="hand2")
link5.grid(row=2,column=0)
link6 =Button(win, text="Pinterest",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest6, cursor="hand2")
link6.grid(row=2,column=1)
link7 =Button(win, text="Reddit",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest7, cursor="hand2")
link7.grid(row=2,column=2)
link8 =Button(win, text="YouTube",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest8, cursor="hand2")
link8.grid(row=2,column=3)
link9 =Button(win, text="WhatsApp",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest9, cursor="hand2")
link9.grid(row=3,column=0)
link10 =Button(win, text="Snapchat",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest10, cursor="hand2")
link10.grid(row=3,column=1)
link11 =Button(win, text="Quora",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest11, cursor="hand2")
link11.grid(row=3,column=2)
link12 =Button(win, text="Medium",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest12, cursor="hand2")
link12.grid(row=3,column=3)
link13 =Button(win, text="WeChat",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest13,cursor="hand2")
link13.grid(row=2,column=4)
link14 =Button(win, text="Stack Overflow",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest14, cursor="hand2")
link14.grid(row=1,column=4)
link15 =Button(win, text="Piazza",font=('Helveticabold', 15), fg="blue",padx=20,compound="top",image=imagetest15, cursor="hand2")
link15.grid(row=1,column=5)


link1.bind("<Button-1>", lambda e:callback("https://www.instagram.com/accounts/login/"))
link2.bind("<Button-1>", lambda e:callback("https://www.facebook.com/"))
link3.bind("<Button-1>", lambda e:callback("https://twitter.com/login?lang=en"))
link4.bind("<Button-1>", lambda e:callback("https://www.linkedin.com/login"))
link5.bind("<Button-1>", lambda e:callback("https://discord.com/"))
link6.bind("<Button-1>", lambda e:callback("https://in.pinterest.com/login/"))
link7.bind("<Button-1>", lambda e:callback("https://www.reddit.com/login/"))
link8.bind("<Button-1>", lambda e:callback("https://www.youtube.com/account"))
link9.bind("<Button-1>", lambda e:callback("https://web.whatsapp.com/login"))
link10.bind("<Button-1>", lambda e:callback("https://accounts.snapchat.com/"))
link11.bind("<Button-1>", lambda e:callback("https://www.quora.com/login"))
link12.bind("<Button-1>", lambda e:callback("https://medium.com/"))
link13.bind("<Button-1>", lambda e:callback("https://www.wechat.com/"))
link14.bind("<Button-1>", lambda e:callback("https://stackoverflow.com/users/login"))
link15.bind("<Button-1>", lambda e:callback("https://piazza.com/account/login"))
Quits = Button(win,text="Exit this window",font=('Helveticabold', 30),fg="green",cursor="hand2",padx=100,pady=30,command=win.quit).grid(columnspan=4,row=5,column=0)
win.mainloop()